# -*- coding: utf-8 -*-
"""feautures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgTvTkOLc27RIjmNcuMyi-7pI5Zjjnd7
"""

"""
Feature extraction for MECO eye-tracking data.
"""

import numpy as np
import pandas as pd
from wordfreq import word_frequency

from src.config import Z_SCORE_COLS


def add_word_length(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add word length feature.
    """
    df = df.copy()
    df["word_len"] = df["word"].str.len()
    return df


def add_word_frequency(df: pd.DataFrame, lang: str = "ru") -> pd.DataFrame:
    """
    Add word frequency and log-frequency features.
    """
    df = df.copy()
    df["freq"] = df["word"].apply(
        lambda w: word_frequency(w.lower(), lang)
    )
    df["log_freq"] = np.log1p(df["freq"])
    return df


def zscore_durations(df: pd.DataFrame) -> pd.DataFrame:
    """
    Z-score normalize fixation duration measures.
    """
    df = df.copy()

    for col in Z_SCORE_COLS:
        if col in df.columns:
            mean = df[col].mean()
            std = df[col].std()
            df[col + "_z"] = (df[col] - mean) / std

    return df


def remove_duration_outliers(
    df: pd.DataFrame,
    z_col: str = "dur_z",
    threshold: float = 3.0,
) -> pd.DataFrame:
    """
    Remove duration outliers based on z-score threshold.
    """
    if z_col not in df.columns:
        raise KeyError(f"{z_col} not found in DataFrame")

    return df[df[z_col].abs() <= threshold].copy()


def add_meco_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Full MECO feature pipeline.
    """
    df = add_word_length(df)
    df = add_word_frequency(df)
    df = zscore_durations(df)
    df = remove_duration_outliers(df)
    return df