# -*- coding: utf-8 -*-
"""load_m.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Go7U0N4ZBBEaa7Rse1iQ-TMSuVig6yNg
"""

"""
Loading MECO eye-tracking data from .rda files.
"""

import rdata
import pandas as pd
from src.config import MECO_RDA_PATH


def load_meco_rda(path=MECO_RDA_PATH):
    """
    Load MECO joint eye-tracking data from an .rda file.

    Parameters
    ----------
    path : str or Path
        Path to the MECO .rda file.

    Returns
    -------
    pd.DataFrame
        Full MECO joint dataset.
    """
    parsed = rdata.parser.parse_file(path)
    converted = rdata.conversion.convert(parsed)

    if "joint.data" not in converted:
        raise KeyError("Expected 'joint.data' in MECO .rda file")

    df = pd.DataFrame(converted["joint.data"])
    return df


def select_language(df, lang="ru_mo"):
    """
    Select a single language from the MECO dataset.

    Parameters
    ----------
    df : pd.DataFrame
        MECO dataset.
    lang : str
        Language code (e.g. 'ru_mo').

    Returns
    -------
    pd.DataFrame
        Language-specific MECO data.
    """
    if "lang" not in df.columns:
        raise KeyError("'lang' column not found in MECO data")

    return df[df["lang"] == lang].copy()