# -*- coding: utf-8 -*-
"""preprocess_m.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVx-ElpDqWNwunWcRIDn86wNrjbunI5P
"""

"""
Preprocessing of MECO eye-tracking data.
"""

import re
import pandas as pd

from src.config import (
    MIN_FIRSTFIX_MS,
    MAX_DUR_MS,
    BINARY_COLS,
)


def preprocess_meco(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply standard preprocessing to MECO data:
    - remove empty tokens
    - keep only Cyrillic words
    - apply duration thresholds (MECO paper)
    - binarize predictors

    Parameters
    ----------
    df : pd.DataFrame
        Raw MECO data (single language).

    Returns
    -------
    pd.DataFrame
        Preprocessed MECO data.
    """

    df = df.copy()

    # remove empty / missing words
    df = df[df["word"].notna()]
    df = df[df["word"].str.strip() != ""]

    # keep only Cyrillic words
    df = df[df["word"].apply(
        lambda w: bool(re.search(r"[А-Яа-яЁё]", str(w)))
    )]

    # duration thresholds (MECO article)
    if "firstfix.dur" in df.columns:
        df = df[
            (df["firstfix.dur"].isna()) |
            (df["firstfix.dur"] >= MIN_FIRSTFIX_MS)
        ]

    if "dur" in df.columns:
        df = df[
            (df["dur"].isna()) |
            (df["dur"] <= MAX_DUR_MS)
        ]

    # binarize predictors
    for col in BINARY_COLS:
        if col in df.columns:
            df[col] = df[col].fillna(0).astype(int)

    return df