# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXkvaP9bMYtTUtgQ8Tts2DgYZ8rKpnEW
"""

# -*- coding: utf-8 -*-
"""
Regression models for MECO eye-tracking data.
"""

import pandas as pd
import statsmodels.api as sm

from src.config import MECO_PREDICTORS, TARGET_VAR


def prepare_regression_data(
    df: pd.DataFrame,
    predictors=MECO_PREDICTORS,
    target: str = TARGET_VAR,
) -> pd.DataFrame:
    """
    Prepare data for regression:
    - select predictors and target
    - coerce to numeric
    - drop missing values
    """
    cols = predictors + [target]
    data = df[cols].copy()
    data = data.apply(pd.to_numeric, errors="coerce")
    data = data.dropna().astype(float)
    return data


def add_first_occurrence_flag(df: pd.DataFrame) -> pd.DataFrame:
    """
    Mark the FIRST GLOBAL occurrence of each unique word.

    IMPORTANT:
    This function assumes that the flag is added BEFORE any
    outlier removal or row filtering that could remove the
    true first occurrence of a word.

    Correct definition:
    - first_occurrence == 1 iff this is the first time the word
      appears in the corpus (global order), NOT per item or sentence.
    """
    df = df.copy()

    df["first_occurrence"] = (
        df.groupby("word").cumcount() == 0
    ).astype(int)

    return df


def fit_ols(
    df: pd.DataFrame,
    predictors=MECO_PREDICTORS,
    target: str = TARGET_VAR,
):
    """
    Fit OLS regression model.
    """
    data = prepare_regression_data(df, predictors, target)
    X = sm.add_constant(data[predictors])
    y = data[target]
    return sm.OLS(y, X).fit()


def fit_ols_full_and_first_occurrence(
    df: pd.DataFrame,
    predictors=MECO_PREDICTORS,
    target: str = TARGET_VAR,
):
    """
    Fit OLS on:
    (1) Full MECO data
    (2) First occurrence of each unique word (global)

    Returns
    -------
    lm_full : OLS results for full dataset
    lm_first : OLS results for first occurrences only
    """

    # Full data
    lm_full = fit_ols(df, predictors, target)

    # First occurrences (global, word-level)
    df = add_first_occurrence_flag(df)
    df_first = df[df["first_occurrence"] == 1]

    print("\nData splits:")
    print(f"  Full MECO: {len(df)} observations")
    print(f"  First occurrences: {len(df_first)} observations")
    print(f"  Unique words: {df['word'].nunique()}")

    lm_first = fit_ols(df_first, predictors, target)

    print("\n" + "=" * 80)
    print("OLS REGRESSION RESULTS — FULL MECO")
    print("=" * 80)
    print(lm_full.summary())

    print("\n" + "=" * 80)
    print("OLS REGRESSION RESULTS — FIRST OCCURRENCES ONLY")
    print("=" * 80)
    print(lm_first.summary())

    return lm_full, lm_first


def average_by_word(
    df: pd.DataFrame,
    predictors=MECO_PREDICTORS,
    target: str = TARGET_VAR,
    group_cols=None,
) -> pd.DataFrame:
    """
    Average MECO data across observations, word by word.
    This yields a type-level (word-level) dataset.
    """
    if group_cols is None:
        group_cols = ["word"]

    avg_df = (
        df
        .groupby(group_cols)[predictors + [target]]
        .mean()
        .reset_index()
    )

    return avg_df