# -*- coding: utf-8 -*-
"""difficulty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10a1o41jeKXMwQfkp8fOABfAZJiLkt6Uw
"""

# -*- coding: utf-8 -*-
"""
Reading difficulty estimation using surprisal transfer.
"""

import numpy as np
from typing import Tuple, List

from src.surprisal.en import EnglishSurprisalModel, sentence_to_words


class DifficultyModel:
    """
    Gaze-informed reading difficulty model.

    Per-word difficulty:
        diff = b0 + b_s * surprisal
    """

    def __init__(
        self,
        surprisal_model: EnglishSurprisalModel,
        b0: float,
        b_s: float,
    ):
        self.surprisal_model = surprisal_model
        self.b0 = b0
        self.b_s = b_s

    def word_difficulties(self, sentence: str) -> List[float]:
        """
        Compute per-word difficulty scores.
        """
        words = sentence_to_words(sentence)
        surprisals = self.surprisal_model.sentence_surprisal(words)

        diffs = []
        for s in surprisals:
            if s is None or np.isnan(s):
                continue
            diffs.append(self.b0 + self.b_s * s)

        return diffs

    def sentence_difficulty(
        self,
        sentence: str,
    ) -> Tuple[float | None, float | None]:
        """
        Compute mean and variance of reading difficulty for a sentence.
        """
        diffs = self.word_difficulties(sentence)

        if len(diffs) == 0:
            return None, None

        mean_d = float(np.mean(diffs))
        var_d = float(np.var(diffs))

        return mean_d, var_d