# -*- coding: utf-8 -*-
"""rerank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybiHBosQh3XvCgINwxQz8DVIoJhJiTBr
"""

"""
Reranking of MT candidates using gaze-informed difficulty.
"""

from typing import List, Dict

from src.gaze_mt.difficulty import DifficultyModel
from src.config import ALPHA, BETA


def score_candidates(
    candidates: List[str],
    log_probs: List[float],
    difficulty_model: DifficultyModel,
    alpha: float = ALPHA,
    beta: float = BETA,
) -> List[Dict]:
    """
    Score MT candidates using gaze-informed difficulty.
    combined_score = log_prob - alpha * mean_difficulty - beta * variance
    """
    scored = []

    for cand, logp in zip(candidates, log_probs):
        mean_d, var_d = difficulty_model.sentence_difficulty(cand)

        if mean_d is None:
            continue

        combined = logp - alpha * mean_d - beta * var_d

        scored.append({
            "translation": cand,
            "logp": logp,
            "mean_difficulty": mean_d,
            "variance": var_d,
            "combined_score": combined,
        })

    return scored


def select_best(scored_candidates: List[Dict]) -> Dict[str, Dict]:
    """
    Select baseline and gaze-informed best translations.
    """
    if len(scored_candidates) == 0:
        raise ValueError("No scored candidates to select from")

    baseline = max(scored_candidates, key=lambda x: x["logp"])
    gaze_best = max(scored_candidates, key=lambda x: x["combined_score"])

    return {
        "baseline": baseline,
        "gaze_best": gaze_best,
    }