# -*- coding: utf-8 -*-
"""load_w.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfUyBbjehm97Pw2hRt5ruJ2sXwjQShfB
"""

"""
Loading WMT News Commentary parallel data.
"""

import pandas as pd
from src.config import WMT_TSV_PATH


def load_wmt(path=WMT_TSV_PATH) -> pd.DataFrame:
    """
    Load WMT News Commentary EN-RU data.

    Parameters
    ----------
    path : str or Path
        Path to the WMT .tsv file.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns ['en', 'ru'].
    """
    df = pd.read_csv(
        path,
        sep="\t",
        header=None,
        quoting=3,
        on_bad_lines="skip"
    )

    if df.shape[1] < 2:
        raise ValueError("WMT file must contain at least two columns")

    df = df.iloc[:, :2]
    df.columns = ["en", "ru"]

    return df