# -*- coding: utf-8 -*-
"""preprocess_w.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0S2sEFdN5yUIx39SJ-0DP-mY4kFiduG
"""

"""
Preprocessing for WMT News Commentary data.
"""

import re
import pandas as pd

from src.config import MAX_SENT_LEN_WORDS


def clean_ru_text(text: str) -> str:
    """
    Basic cleanup of Russian text.
    """
    if not isinstance(text, str):
        return ""

    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    text = text.replace("–", "-")
    text = text.replace("\ufeff", "")
    return text


def preprocess_wmt(
    df: pd.DataFrame,
    max_len: int = MAX_SENT_LEN_WORDS,
) -> pd.DataFrame:
    """
    Preprocess WMT data:
    - clean Russian text
    - remove empty rows
    - compute sentence length in words
    - filter by maximum length
    """
    df = df.copy()

    # clean RU text
    df["ru_clean"] = df["ru"].apply(clean_ru_text)

    # remove empty
    df = df[df["ru_clean"] != ""]

    # sentence length
    df["len_words"] = df["ru_clean"].apply(
        lambda x: len(x.split())
    )

    # length filter
    df = df[df["len_words"] <= max_len]

    return df.reset_index(drop=True)