# -*- coding: utf-8 -*-
"""ru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTnanGlOm4R7Gpwp60bA_SHa2BUE-ClV
"""

"""
Russian surprisal computation using a causal language model.
"""

import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm.auto import tqdm

from src.config import RU_GPT_MODEL


class RussianSurprisalModel:
    """
    Wrapper for computing word-level surprisal in Russian.
    """

    def __init__(self, model_name: str = RU_GPT_MODEL, device: str | None = None):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(model_name)

        if device is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"

        self.device = device
        self.model.to(self.device)
        self.model.eval()

    @torch.no_grad()
    def sentence_surprisal(self, words: list[str]) -> list[float]:
        """
        Compute surprisal for a sequence of words.
        The first word receives NaN (no context).
        """
        surprisals = []
        context_ids = None

        for w in words:
            word_ids = self.tokenizer.encode(
                " " + w,
                add_special_tokens=False
            )

            if context_ids is None:
                context_ids = torch.tensor([word_ids], device=self.device)
                surprisals.append(np.nan)
                continue

            total_surprisal = 0.0
            ids = context_ids.clone()

            for token_id in word_ids:
                logits = self.model(ids).logits
                log_probs = torch.log_softmax(logits[0, -1], dim=-1)
                total_surprisal += -log_probs[token_id].item()

                ids = torch.cat(
                    [ids, torch.tensor([[token_id]], device=self.device)],
                    dim=1
                )

            surprisals.append(total_surprisal)
            context_ids = ids

        return surprisals


def add_ru_surprisal(
    df,
    model: RussianSurprisalModel,
    group_cols=("subid", "trialid", "sentnum"),
    sort_cols=("subid", "trialid", "sentnum", "wordnum"),
):
    """
    Compute surprisal for MECO Russian data and add it as a column.
    Assumes df contains columns: word, subid, trialid, sentnum, wordnum.
    """
    df = df.sort_values(list(sort_cols)).copy()

    surprisal_values = []

    for _, group in tqdm(
        df.groupby(list(group_cols)),
        desc="Computing RU surprisal"
    ):
        words = group["word"].tolist()
        s = model.sentence_surprisal(words)
        surprisal_values.extend(s)

    df["surprisal"] = surprisal_values
    return df