# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1rUJAuY5Jt2aG-trkGUkF6_tjDVQ4qV
"""

"""
Contains:
- project paths
- dataset locations
- model names
- experiment hyperparameters
"""

from pathlib import Path

# Project root
# src/config.py -> src -> project root
ROOT = Path(__file__).resolve().parents[1]

# Data directories
DATA_DIR = ROOT / "data"

# MECO
MECO_DIR = DATA_DIR / "meco"
MECO_RDA_PATH = MECO_DIR / "joint_data_trimmed_wave2_version2.0.rda"

# WMT
WMT_DIR = DATA_DIR / "wmt"
WMT_TSV_PATH = WMT_DIR / "news-commentary-v18.en-ru.tsv"

# Results
RESULTS_DIR = ROOT / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
TABLES_DIR = RESULTS_DIR / "tables"

# Language models
# Russian GPT for surprisal
RU_GPT_MODEL = "ai-forever/rugpt3small_based_on_gpt2"

# English GPT for surprisal transfer
EN_GPT_MODEL = "gpt2"

# MT model (RU -> EN)
MT_RU_EN_MODEL = "Helsinki-NLP/opus-mt-ru-en"

# MECO preprocessing
# Duration thresholds (as in MECO paper)
MIN_FIRSTFIX_MS = 80
MAX_DUR_MS = 3000

# Columns to z-score
Z_SCORE_COLS = [
    "firstfix.dur",
    "firstrun.dur",
    "dur",
    "singlefix.dur",
]

# Binary predictors
BINARY_COLS = ["skip", "reread"]

# Regression model
MECO_PREDICTORS = [
    "surprisal",
    "log_freq",
    "word_len",
]

TARGET_VAR = "dur_z"

# WMT preprocessing
MAX_SENT_LEN_WORDS = 40

# Gaze-informed MT
NUM_BEAMS = 5

# Reranking weights
ALPHA = 1.0   # mean difficulty weight
BETA = 0.5    # variance penalty

# Evaluation
EVAL_SAMPLE_SIZE = 50
RANDOM_SEED = 42